# Inventaire SEC-OPS LAB
# Réseau interne : labnet (192.168.10.0/24)

[ubuntu_cible]
ubuntu1 ansible_host=192.168.10.10 ansible_user=ubunto ansible_become=yes

[kali_tests]
kali1 ansible_host=192.168.10.30 ansible_user=kali ansible_become=yes

[all_targets:children]
ubuntu_cible
kali_tests
